<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Task;
use App\Models\Team;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Schema;

class ChatbotController extends Controller
{
    public function handleMessage(Request $request)
    {
        try {
            $userMessage = $request->input('message');
            
            // Get logged-in user
            $user = Auth::user();
            if (!$user) {
                return response()->json([
                    'reply' => '❌ Please log in first!'
                ]);
            }
            
            $currentUserId = $user->id;
            $userRole = strtolower($user->role);

            // =========================================================
            // 🛡️ ROLE SECURITY - MEMBERS ONLY VIEW ALLOWED
            // =========================================================
            if ($userRole !== 'admin' && preg_match('/(create|add|make)/i', $userMessage)) {
                return response()->json([
                    'reply' => "❌ Sorry, only Admins can create tasks! You can only view your assigned tasks.",
                    'action_taken' => 'denied'
                ]);
            }

            // =========================================================
            // MODULE 1: 👥 CREATE TEAM (ADMIN ONLY)
            // =========================================================
            if ($userRole === 'admin' && preg_match('/(create|add|make).+team/i', $userMessage)) {
                
                // Extract team name from message
                $teamName = preg_replace('/(create|add|make|a|new|team|named|called|for)/i', '', $userMessage);
                $teamName = trim(str_replace(['"', "'"], '', $teamName));
                
                if (empty($teamName)) {
                    $teamName = 'New Team ' . now()->format('H:i');
                }

                // Create team
                $team = Team::create([
                    'name' => $teamName,
                    'description' => 'Auto-generated by Smart Task Assistant',
                    'admin_id' => $currentUserId
                ]);

                return response()->json([
                    'reply' => "✅ Team **{$team->name}** created successfully! Go to Teams Management to manage it.",
                    'action_taken' => 'create_team',
                    'team_id' => $team->id
                ]);
            }

            // =========================================================
            // MODULE 2: 📝 CREATE TASK (ADMIN ONLY)
            // =========================================================
            if ($userRole === 'admin' && preg_match('/(create|add|make).+task/i', $userMessage)) {
                
                // Extract task title
                $title = preg_replace('/(create|add|make|a|new|task|high|priority|for|by|tomorrow|today)/i', '', $userMessage);
                $title = trim(str_replace(['"', "'"], '', $title));
                
                if (empty($title)) {
                    $title = 'New Task via AI Assistant';
                }

                // Detect priority
                $priority = 'Medium';
                if (preg_match('/high/i', $userMessage)) {
                    $priority = 'High';
                } elseif (preg_match('/low/i', $userMessage)) {
                    $priority = 'Low';
                }

                // Detect category
                $category = 'Personal';
                if (preg_match('/(work|project)/i', $userMessage)) {
                    $category = 'Work';
                } elseif (preg_match('/(study|learn|exam)/i', $userMessage)) {
                    $category = 'Study';
                } elseif (preg_match('/(team|group)/i', $userMessage)) {
                    $category = 'Team';
                }

                // Detect deadline
                $deadline = now()->addDays(1);
                if (preg_match('/tomorrow/i', $userMessage)) {
                    $deadline = now()->addDays(1);
                } elseif (preg_match('/(today|asap)/i', $userMessage)) {
                    $deadline = now()->addHours(6);
                } elseif (preg_match('/week/i', $userMessage)) {
                    $deadline = now()->addWeek();
                }

                // Find assigned user
                $assignedUserId = $currentUserId;
                $allUsers = User::all();
                
                foreach ($allUsers as $dbUser) {
                    if (preg_match('/' . preg_quote(strtolower($dbUser->name), '/') . '/i', $userMessage)) {
                        $assignedUserId = $dbUser->id;
                        break;
                    }
                }

                // Create task
                $task = Task::create([
                    'title' => $title,
                    'description' => 'Auto-generated by Smart Task Assistant',
                    'category' => $category,
                    'priority' => $priority,
                    'status' => 'Pending',
                    'assigned_by' => $currentUserId,
                    'assigned_to' => $assignedUserId,
                    'deadline' => $deadline
                ]);

                return response()->json([
                    'reply' => "✅ Task **{$task->title}** created! Priority: {$priority}, Category: {$category}, Deadline: " . $deadline->format('M d, Y'),
                    'action_taken' => 'create_task',
                    'task_id' => $task->id
                ]);
            }

            // =========================================================
            // DEFAULT: Chat response (for both admin and members)
            // =========================================================
            $botReply = $this->getBotResponse($userMessage, $user);

            return response()->json([
                'reply' => $botReply,
                'action_taken' => 'chat'
            ]);

        } catch (\Exception $e) {
            return response()->json([
                'reply' => '❌ Error: ' . $e->getMessage(),
                'action_taken' => 'error'
            ], 500);
        }
    }

    // Simple bot response generator
    private function getBotResponse($message, $user)
    {
        $message = strtolower($message);
        $userName = explode(' ', $user->name)[0];

        if (preg_match('/(hello|hi|hey)/i', $message)) {
            return "👋 Hi {$userName}! I'm your Smart Task Assistant. How can I help?";
        }

        if (preg_match('/(create|add|make).+task/i', $message)) {
            if ($user->role !== 'admin') {
                return "❌ Only admins can create tasks!";
            }
            return "📝 I can help create a task! Tell me the title, priority, and deadline.";
        }

        if (preg_match('/(create|add|make).+team/i', $message)) {
            if ($user->role !== 'admin') {
                return "❌ Only admins can create teams!";
            }
            return "👥 Let's create a team! What should we call it?";
        }

        if (preg_match('/(my|view).+tasks/i', $message)) {
            $count = $user->tasks()->count();
            return "📋 You have **{$count}** tasks assigned to you!";
        }

        if (preg_match('/(help|what can you do)/i', $message)) {
            return "🤖 I can help you:\n- Create tasks (admins only)\n- Create teams (admins only)\n- View your tasks\n- Answer questions about your workload";
        }

        return "I understand you want to: **{$message}**. How can I help you manage your tasks?";
    }
}